### ISSUE TITLE
Tag Match Page

### ISSUE THREAD

**Issue by jerryshi042003** [awest25/Tennis-Video-Viewer#15]
This should be merged/collaborated with #23 

Using run local, then adding /tag-match in url, you can access this page.

Keywords
spacebar: pause/play
d: add start point timestamp
f: add end point timestamp
r: forward 1 frame
e: backward 1 frame
w: forward 5 sec
q: backward 5 sec
s: forward 10 sec
a: backward 10 sec
2 (number): 2x speed
1 (number): 1x speed

FIXING FEATURE:
1. Two columns should be linked such that each row always moves together
2. When you delete a value from column, all values move up one row to fill it.

2 (Further) If there is a gap, like 
some value [pre-existing value]
no value [null]
then you type some value here [typed value]

the no value row adds whatever is in your typed value 

ADDING NEW FEATURE:

Add title to left of row "Point x"

Add clickable link to right of row that says "Click for Point" and it changes timestamp of video to start of the point and either
1. ends where point ends
2. add millisecond timestamp that shows where video is playing 
Goal: so we can reference the end of point timestamp is correct

**Comment by Fredenck** [comment]
functionality to support requested features:
- can't spam d or f to create more rows
- requires f to complete the point after d
- auto sort in case tagger misses a point

**Comment by awest25** [comment]
There are still a few features left to implement:

1. Add an explanation of the controls to the tag-match page.
2. If a row is completely blank, it should be removed instead of remaining in the time list.
3. A "Play Point" button that will jump to the beginning of the point and play until the point is over and pause.
4. Duration conversion: at some point, the rows must be converted to a start time and duration measurement.
